name: Publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    uses: ZenGo-X/multi-party-ecdsa/.github/workflows/build.yml@master
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish crate
        env:
          TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish --token "$TOKEN"
